language: java
script: "mvn package"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  skip_cleanup: true
  region: "us-east-2"
  app: "SheetQL"
  env: "Sheetql2-env-test"
  bucket_name: "elasticbeanstalk-us-east-2-509229788800"
  zip_file: target/solo-sheetql-0.0.1-SNAPSHOT.war
  on:
    branch: development

after_success:
  - echo "build successful"