language: java
script: "mvn test"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-east-2"
  app: "SheetQL-2"
  env: "Sheetql2-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-509229788800"
  on:
    branch: development


after_success:
  - echo "build successful"